name: Multi-arch release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21]
        arch: [amd64, arm64, ppc64le]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build and publish for ${{ matrix.arch }}
        run: |
          env GOARCH=${{ matrix.arch }} go build -o  mastodon_prometheus_exporter_${{ matrix.arch }}
          # Add steps to publish the artifact
          echo "Publishing artifact for ${{ matrix.arch }}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mastodon_prometheus_exporter_${{ matrix.arch }}
          path: mastodon_prometheus_exporter_${{ matrix.arch }}
